# Generated by Django 5.2.8 on 2025-11-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_fin_especial',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de la Oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='fecha_inicio_especial',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de la Oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_especial',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio Especial (Oferta)'),
        ),
    ]
