# Generated by Django 5.2.8 on 2025-11-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='local_asignado',
            field=models.CharField(blank=True, choices=[('a', 'Local 1 (Base de Datos A)'), ('b', 'Local 2 (Base de Datos B)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('local', 'Local')], default='estudiante', max_length=10),
        ),
    ]
