# Generated by Django 5.2.8 on 2025-11-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_local_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagojunaeborder',
            name='estado_local_a',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RETIRADO', 'Retirado'), ('NA', 'No Aplica')], default='NA', max_length=10, verbose_name='Estado Local A'),
        ),
        migrations.AddField(
            model_name='pagojunaeborder',
            name='estado_local_b',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RETIRADO', 'Retirado'), ('NA', 'No Aplica')], default='NA', max_length=10, verbose_name='Estado Local B'),
        ),
        migrations.AddField(
            model_name='webpayorder',
            name='estado_local_a',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RETIRADO', 'Retirado'), ('NA', 'No Aplica')], default='NA', max_length=10, verbose_name='Estado Local A'),
        ),
        migrations.AddField(
            model_name='webpayorder',
            name='estado_local_b',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RETIRADO', 'Retirado'), ('NA', 'No Aplica')], default='NA', max_length=10, verbose_name='Estado Local B'),
        ),
    ]
