# Generated by Django 5.2.8 on 2025-11-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagojunaeborder_estado_local_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='origin',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='favorite',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='favorite',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product_id', 'origin')},
        ),
    ]
