# Generated by Django 5.2.8 on 2025-11-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_favorite_origin_favorite_price_favorite_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(choices=[('a', 'Local 1 (Base de Datos A)'), ('b', 'Local 2 (Base de Datos B)')], max_length=1)),
                ('imagen', models.ImageField(upload_to='carrusel_promos/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('tipo_link', models.CharField(choices=[('tienda', 'Ir a mi Tienda'), ('producto', 'Ir a un Producto Específico')], default='tienda', max_length=10)),
                ('producto_id', models.IntegerField(blank=True, default=0, help_text="ID del producto (solo si eliges 'Producto Específico')")),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(choices=[('a', 'Local 1 (Base de Datos A)'), ('b', 'Local 2 (Base de Datos B)')], max_length=1, unique=True)),
                ('nombre_local', models.CharField(default='Mi Local', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='Descripción del local...')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_locales/')),
            ],
        ),
    ]
