# Generated by Django 5.2.8 on 2025-12-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carouselitem_localprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='localprofile',
            name='color_banner',
            field=models.CharField(default='#004aad', max_length=7),
        ),
    ]
